---
- name: Dependencies
  apt: name={{item}} state=present update_cache=yes install_recommends=no

  with_items:
    - git
    - sudo
    - python-pip
    - python-pkg-resources
    - python-setuptools
    - gzip
    - unzip
    - curl
    - apt-transport-https
    - openssl
    - tzdata
    - nano
    - dstat
    - htop

- name: Locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Updating locale
  command: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
  changed_when: false

- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  when: 'drs_disable_ipv6 is defined and drs_disable_ipv6 == True'

- name: Seting timezone to UTC
  timezone:
    name: Etc/UTC
  ignore_errors: yes

- name: Installing ntp
  apt: name=ntp state=present

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp=".*#ansible_line$" line="127.0.0.1    {{ inventory_hostname_short|default(inventory_hostname) + ' '}}#ansible_line" state=present
  tags: ['hostname']

- name: Changing hostname to match inventory_hostname_short
  hostname:
    name: "{{ inventory_hostname_short|default(inventory_hostname) }}"
  register: "hostname_status"
  when: ansible_hostname != inventory_hostname_short|default(inventory_hostname)
  ignore_errors: yes
  tags: ['hostname']

- include_tasks: user.yml
  when: drs_setup_user is defined and drs_setup_user == True and ansible_user != drs_user
  tags: ['user']

- name: Add ssh agent line to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: SSH_AUTH_SOCK
    line: Defaults env_keep += "SSH_AUTH_SOCK"
  tags: ['become-agent']

- name: Creating data directory with selected user as owner
  file:
    path: '{{drs_data_dir}}'
    state: directory
    mode: 0755
    recurse: yes
    group: '{{drs_user}}'
    owner: '{{drs_user}}'
  when: drs_data_dir is defined and drs_data_dir

