- name: Creating user group
  group:
    name: '{{ drs_user }}'
    state: present

- name: Creating user
  user:
    name: '{{ drs_user }}'
    password: '{{ drs_pass|default(omit) }}'
#    ssh_key_type: '.ssh/id_rsa'
    group: '{{ drs_user }}'
    groups: sudo
    shell: /bin/bash

- name: Adding SSH keys
  authorized_key:
    user: '{{ drs_user }}'
    state: present
    key: '{{ item }}'
  with_file:
    - '{{drs_pub_key_file}}'
  when: drs_pub_key_file is defined and drs_pub_key_file != None
  ignore_errors: yes

- name: Adding to sudoers
  lineinfile: dest='/etc/sudoers' state='present' regexp='^{{drs_user}} ' line='{{drs_user}} ALL=(ALL:ALL) NOPASSWD:ALL'

