- name: Creating user group
  group:
    name: '{{ drs_user }}'
    gid: "{{ drs_gid|default(omit) }}"
    state: present

- name: Creating user
  user:
    name: '{{ drs_user }}'
    password: '{{ drs_pass|default(omit) }}'
    group: '{{ drs_user }}'
    home: "{{drs_home_dir|default(omit)}}"
    shell: /bin/bash
    groups: sudo
    uid: "{{drs_uid|default(omit)}}"

- name: Adding SSH keys
  authorized_key:
    user: '{{ drs_user }}'
    state: "{{ r_authorized_key_remove | ternary('absent', 'present') }}"
    key: '{{ item }}'
  with_file:
    - '{{drs_pub_key_file}}'
  when: drs_pub_key_file is defined and drs_pub_key_file != None
  ignore_errors: yes

- name: Adding to sudoers
  lineinfile: dest='/etc/sudoers' state='present' regexp='^{{drs_user}} ' line='{{drs_user}} ALL=(ALL:ALL) NOPASSWD:ALL'

